### ISSUE TITLE
Encrypt RDS instances

### ISSUE THREAD

**Issue by dlapiduz** [18F/aws-broker#15]
In order for RDS instances created by the broker to be compliant they need to be encrypted.

* [x] Shared RDS instances are encrypted
* [x] Dedicated RDS instances are encrypted

**Comment by jmcarp** [comment]
Fun fact: the `micro-psql` and `micro-mysql` plans use the `t2-micro` instance type, which doesn't support encryption: http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.Encryption.html. We should be able to encrypt the shared instances and dedicated medium instances though.

**Comment by mogul** [comment]
We should be documenting that in the plan descriptions, so people know what trade-off they're getting when they pick one vs another.

**Comment by dlapiduz** [comment]
@jmcarp this was addressed with the plans change, right?

**Comment by jmcarp** [comment]
Yep, this is done.
