### ISSUE TITLE
Allow users to configure allocated storage

### ISSUE THREAD

**Issue by jmcarp** [18F/aws-broker#20]
At the moment, all plans allocate 10gb. Some users might want more. We could either build storage allocation into our plans (this is already done in https://github.com/cf-platform-eng/rds-broker), or preferably allow users to configure storage on provision and update.

Can be changed on this repo or https://github.com/cf-platform-eng/rds-broker.

**Comment by sharms** [comment]
Tested and validated by making a Postgres DB with 50GB -
 can we close this one out?

https://cloud.gov/docs/services/relational-database/#create-an-instance
